Fix flaky test
observed several failures due to

```
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:459)
	at java.base/sun.nio.ch.Net.bind(Net.java:448)
	at java.base/sun.nio.ch.AsynchronousServerSocketChannelImpl.bind(AsynchronousServerSocketChannelImpl.java:164)
	at org.apache.sshd.common.io.nio2.Nio2Acceptor.bind(Nio2Acceptor.java:83)
	at org.apache.sshd.common.io.nio2.Nio2Acceptor.bind(Nio2Acceptor.java:173)
	at org.apache.sshd.server.SshServer.start(SshServer.java:331)
	at com.cloudbees.jenkins.plugins.sshagent.SSHAgentBase.startMockSSHServer(SSHAgentBase.java:171)
```

rather than obtain a port ant t1 and then use it later at t2 just get the SSH server to use a port and then find out which port is actually being used.